//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.22 at 11:51:16 AM CEST 
//


package de.unikassel.puma.openaccess.sword.renderer.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.bibsonomy.rest.renderer.xml.PostType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{}PostType">
 *       &lt;sequence>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="examinstitution" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="examreferee" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="phdoralexam" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="sponsors" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="additionaltitle" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="classification" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="user" type="{http://puma.uni-kassel.de/2010/11/PUMA-SWORD}PumaUserType"/>
 *         &lt;element name="publisherinfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ISBN" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ISSN" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DOI" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="location" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="DCC" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "author",
    "examinstitution",
    "examreferee",
    "phdoralexam",
    "sponsors",
    "additionaltitle",
    "classification",
    "user",
    "publisherinfo"
})
@XmlRootElement(name = "PumaPost", namespace = "http://puma.uni-kassel.de/2010/11/PUMA-SWORD")
public class PumaPost
    extends PostType
{

    @XmlElement(namespace = "http://puma.uni-kassel.de/2010/11/PUMA-SWORD")
    protected List<String> author;
    @XmlElement(namespace = "http://puma.uni-kassel.de/2010/11/PUMA-SWORD")
    protected String examinstitution;
    @XmlElement(namespace = "http://puma.uni-kassel.de/2010/11/PUMA-SWORD")
    protected List<String> examreferee;
    @XmlElement(namespace = "http://puma.uni-kassel.de/2010/11/PUMA-SWORD")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar phdoralexam;
    @XmlElement(namespace = "http://puma.uni-kassel.de/2010/11/PUMA-SWORD")
    protected List<String> sponsors;
    @XmlElement(namespace = "http://puma.uni-kassel.de/2010/11/PUMA-SWORD")
    protected List<String> additionaltitle;
    @XmlElement(namespace = "http://puma.uni-kassel.de/2010/11/PUMA-SWORD")
    protected List<PumaPost.Classification> classification;
    @XmlElement(namespace = "http://puma.uni-kassel.de/2010/11/PUMA-SWORD", required = true)
    protected PumaUserType user;
    @XmlElement(namespace = "http://puma.uni-kassel.de/2010/11/PUMA-SWORD")
    protected String publisherinfo;
    @XmlAttribute(name = "ISBN")
    protected String isbn;
    @XmlAttribute(name = "ISSN")
    protected String issn;
    @XmlAttribute(name = "DOI")
    protected String doi;
    @XmlAttribute
    protected String location;
    @XmlAttribute(name = "DCC")
    protected String dcc;

    /**
     * Gets the value of the author property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the author property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAuthor() {
        if (author == null) {
            author = new ArrayList<String>();
        }
        return this.author;
    }

    /**
     * Gets the value of the examinstitution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExaminstitution() {
        return examinstitution;
    }

    /**
     * Sets the value of the examinstitution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExaminstitution(String value) {
        this.examinstitution = value;
    }

    /**
     * Gets the value of the examreferee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the examreferee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExamreferee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getExamreferee() {
        if (examreferee == null) {
            examreferee = new ArrayList<String>();
        }
        return this.examreferee;
    }

    /**
     * Gets the value of the phdoralexam property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPhdoralexam() {
        return phdoralexam;
    }

    /**
     * Sets the value of the phdoralexam property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPhdoralexam(XMLGregorianCalendar value) {
        this.phdoralexam = value;
    }

    /**
     * Gets the value of the sponsors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sponsors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSponsors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSponsors() {
        if (sponsors == null) {
            sponsors = new ArrayList<String>();
        }
        return this.sponsors;
    }

    /**
     * Gets the value of the additionaltitle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionaltitle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionaltitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAdditionaltitle() {
        if (additionaltitle == null) {
            additionaltitle = new ArrayList<String>();
        }
        return this.additionaltitle;
    }

    /**
     * Gets the value of the classification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PumaPost.Classification }
     * 
     * 
     */
    public List<PumaPost.Classification> getClassification() {
        if (classification == null) {
            classification = new ArrayList<PumaPost.Classification>();
        }
        return this.classification;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link PumaUserType }
     *     
     */
    public PumaUserType getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link PumaUserType }
     *     
     */
    public void setUser(PumaUserType value) {
        this.user = value;
    }

    /**
     * Gets the value of the publisherinfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublisherinfo() {
        return publisherinfo;
    }

    /**
     * Sets the value of the publisherinfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublisherinfo(String value) {
        this.publisherinfo = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISBN() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISBN(String value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the issn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISSN() {
        return issn;
    }

    /**
     * Sets the value of the issn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISSN(String value) {
        this.issn = value;
    }

    /**
     * Gets the value of the doi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOI() {
        return doi;
    }

    /**
     * Sets the value of the doi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOI(String value) {
        this.doi = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocation(String value) {
        this.location = value;
    }

    /**
     * Gets the value of the dcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDCC() {
        return dcc;
    }

    /**
     * Sets the value of the dcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDCC(String value) {
        this.dcc = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="value" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Classification {

        @XmlAttribute
        protected String name;
        @XmlAttribute
        protected String value;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }

}
