//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.27 at 01:17:20 PM CEST 
//


package org.bibsonomy.rest.renderer.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bibsonomyXML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bibsonomyXML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="users" type="{}UsersType"/>
 *           &lt;element name="groups" type="{}GroupsType"/>
 *           &lt;element name="tags" type="{}TagsType"/>
 *           &lt;element name="posts" type="{}PostsType"/>
 *           &lt;element name="user" type="{}UserType"/>
 *           &lt;element name="group" type="{}GroupType"/>
 *           &lt;element name="post" type="{}PostType"/>
 *           &lt;element name="tag" type="{}TagType"/>
 *           &lt;element name="bookmark" type="{}BookmarkType"/>
 *           &lt;element name="bibtex" type="{}BibtexType"/>
 *           &lt;element name="error" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="resourcehash" type="{}hashType"/>
 *           &lt;element name="userid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="groupid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *           &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *           &lt;element name="references" type="{}ReferencesType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="stat" type="{}statType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bibsonomyXML", propOrder = {
    "users",
    "groups",
    "tags",
    "posts",
    "user",
    "group",
    "post",
    "tag",
    "bookmark",
    "bibtex",
    "error",
    "resourcehash",
    "userid",
    "groupid",
    "uri",
    "references"
})
public class BibsonomyXML {

    protected UsersType users;
    protected GroupsType groups;
    protected TagsType tags;
    protected PostsType posts;
    protected UserType user;
    protected GroupType group;
    protected PostType post;
    protected TagType tag;
    protected BookmarkType bookmark;
    protected BibtexType bibtex;
    protected String error;
    protected String resourcehash;
    protected String userid;
    protected String groupid;
    @XmlSchemaType(name = "anyURI")
    protected String uri;
    protected ReferencesType references;
    @XmlAttribute
    protected StatType stat;

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link UsersType }
     *     
     */
    public UsersType getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsersType }
     *     
     */
    public void setUsers(UsersType value) {
        this.users = value;
    }

    /**
     * Gets the value of the groups property.
     * 
     * @return
     *     possible object is
     *     {@link GroupsType }
     *     
     */
    public GroupsType getGroups() {
        return groups;
    }

    /**
     * Sets the value of the groups property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupsType }
     *     
     */
    public void setGroups(GroupsType value) {
        this.groups = value;
    }

    /**
     * Gets the value of the tags property.
     * 
     * @return
     *     possible object is
     *     {@link TagsType }
     *     
     */
    public TagsType getTags() {
        return tags;
    }

    /**
     * Sets the value of the tags property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagsType }
     *     
     */
    public void setTags(TagsType value) {
        this.tags = value;
    }

    /**
     * Gets the value of the posts property.
     * 
     * @return
     *     possible object is
     *     {@link PostsType }
     *     
     */
    public PostsType getPosts() {
        return posts;
    }

    /**
     * Sets the value of the posts property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostsType }
     *     
     */
    public void setPosts(PostsType value) {
        this.posts = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link UserType }
     *     
     */
    public UserType getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserType }
     *     
     */
    public void setUser(UserType value) {
        this.user = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link GroupType }
     *     
     */
    public GroupType getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupType }
     *     
     */
    public void setGroup(GroupType value) {
        this.group = value;
    }

    /**
     * Gets the value of the post property.
     * 
     * @return
     *     possible object is
     *     {@link PostType }
     *     
     */
    public PostType getPost() {
        return post;
    }

    /**
     * Sets the value of the post property.
     * 
     * @param value
     *     allowed object is
     *     {@link PostType }
     *     
     */
    public void setPost(PostType value) {
        this.post = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link TagType }
     *     
     */
    public TagType getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagType }
     *     
     */
    public void setTag(TagType value) {
        this.tag = value;
    }

    /**
     * Gets the value of the bookmark property.
     * 
     * @return
     *     possible object is
     *     {@link BookmarkType }
     *     
     */
    public BookmarkType getBookmark() {
        return bookmark;
    }

    /**
     * Sets the value of the bookmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookmarkType }
     *     
     */
    public void setBookmark(BookmarkType value) {
        this.bookmark = value;
    }

    /**
     * Gets the value of the bibtex property.
     * 
     * @return
     *     possible object is
     *     {@link BibtexType }
     *     
     */
    public BibtexType getBibtex() {
        return bibtex;
    }

    /**
     * Sets the value of the bibtex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BibtexType }
     *     
     */
    public void setBibtex(BibtexType value) {
        this.bibtex = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setError(String value) {
        this.error = value;
    }

    /**
     * Gets the value of the resourcehash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResourcehash() {
        return resourcehash;
    }

    /**
     * Sets the value of the resourcehash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResourcehash(String value) {
        this.resourcehash = value;
    }

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserid() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserid(String value) {
        this.userid = value;
    }

    /**
     * Gets the value of the groupid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupid() {
        return groupid;
    }

    /**
     * Sets the value of the groupid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupid(String value) {
        this.groupid = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUri() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUri(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencesType }
     *     
     */
    public ReferencesType getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencesType }
     *     
     */
    public void setReferences(ReferencesType value) {
        this.references = value;
    }

    /**
     * Gets the value of the stat property.
     * 
     * @return
     *     possible object is
     *     {@link StatType }
     *     
     */
    public StatType getStat() {
        return stat;
    }

    /**
     * Sets the value of the stat property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatType }
     *     
     */
    public void setStat(StatType value) {
        this.stat = value;
    }

}
